name: MIT Science Olympiad
markdown: kramdown
incremental: true
exclude: ["README.md", "TODO.md"]

markdown_ext: "markdown,mkdown,mkdn,mkd,md"

collections:
    blogs:
        output: true
        permalink: /blogs/:name/
