name: MIT Science Olympiad
markdown: kramdown
incremental: true
exclude: ['README.md', 'TODO.md']

collections:
    blogs:
        output: true
        permalink: /blogs/:name/

defaults:
  - scope:
      path: ""     # every file
      type: blogs  # in the blogs collection
    values:
      layout: blog
